### ISSUE TITLE
Migrate Metac codebase to this codebase one initial release setup is done

### ISSUE THREAD

**Issue by AmitKumarDas** [metacontroller/metacontroller#13]
**ProblemStatement**: Several bug fixes, enhancements have gone into this fork https://github.com/AmitKumarDas/metac/ since https://github.com/GoogleCloudPlatform/metacontroller was no longer maintained. It will be good to have metac codebase migrated to this new repo as well. 

This will ensure subsequent projects that depend on metac to start using this new repo.

**Comment by AmitKumarDas** [comment]
depends on #8

**Comment by grzesuav** [comment]
https://github.com/metacontroller/metacontroller/pull/26

**Comment by grzesuav** [comment]
@AmitKumarDas do you have an idea how to do it in easy way  ? I mean assuring that subsequent releases will be compatible ?

I guess firstly  project improvements could be merged (cleanups/ adding tests/ refactoring) and features later ? 

Maybe it would be good to cross-compare features which are missing in metacontroller ?

**Comment by AmitKumarDas** [comment]
@grzesuav Metac & Metacontroller are compatible. There is no change to existing features. Metac has added new features & new test cases (_unit as well as integration tests_).

However, it will be difficult to select these new features & apply against this new home since, we will lose all the commits & the contributions. In addition, it will take huge effort to do this activity.

**Comment by AmitKumarDas** [comment]
If we decide not to merge `Metac` to `Metacontroller` as a single PR then we need to follow these steps:
- **1/** Build related changes
  - Makefile, Dockerfile, go.mod, go.sum, hack folder, etc.
- **2/** Copy metac changes from existing folders & files
  - This will take care of refactoring as well as unit tests
- **3/** Copy metac integration test changes for existing features
- **4/** Copy new folders & files from metac to metacontroller
  - This should take care of new features
  - Include new integration test files

I might have missed some steps. However, above looks good.

**Comment by grzesuav** [comment]
@AmitKumarDas I would go with step-by-step migration, it would be very difficult to follow one giant PR, also all changes will be melted etc. I would start with ordering you posted, we can create separate issues for that, now I am working on https://github.com/metacontroller/metacontroller/issues/20

**Comment by grzesuav** [comment]
@AmitKumarDas how difficult would be to apply work done in https://github.com/AmitKumarDas/metac/issues/136 against current version of metacontroller ?

**Comment by AmitKumarDas** [comment]
> @AmitKumarDas how difficult would be to apply work done in [AmitKumarDas/metac#136](https://github.com/AmitKumarDas/metac/issues/136) against current version of metacontroller ?

It should not be difficult. We need to follow the steps mentioned above. Since the integration test codebase is new it might need latest versions.

**Comment by hypergig** [comment]
By any chance is there a list of improvements / bug fixes? Just curious...

**Comment by AmitKumarDas** [comment]
There are no bug fixes but improvements for sure. Copying the improvements from metac to here will be a good one.

**Comment by grzesuav** [comment]
Closing, if any particular improvement would be good to have here feel free to create issues for them
