### ISSUE TITLE
`Status` in CompositeController isn't set // populated from `sync` response

### ISSUE THREAD

**Issue by grzesuav** [metacontroller/metacontroller#147]
When I was writing one of the exaples, I notice that for `CompositeController` `Status` field is not updated correctly. I navigated issue arount https://github.com/metacontroller/metacontroller/blob/master/controller/composite/controller.go#L622 : ins subsequent method :
```go
if changed := update(current); !changed {
````
https://github.com/metacontroller/metacontroller/blob/master/dynamic/clientset/clientset.go#L194 the updated `current` object have `Status` field, but after invocation :

```go
		if rc.HasSubresource("status") {
			result, err = rc.UpdateStatus(current, metav1.UpdateOptions{})
		} else {
			result, err = rc.Update(current, metav1.UpdateOptions{})
		}
```
`result` does not have it.

Referencing some similar issues from original repo : https://github.com/GoogleCloudPlatform/metacontroller/issues/159 https://github.com/GoogleCloudPlatform/metacontroller/issues/201

**Comment by chenjr0719** [comment]
Hi @grzesuav, I have a similar issue about this. Have you figured out any solution? It only happened when I create CRD with `apiextensions.k8s.io/v1` but works when I use `apiextensions.k8s.io/v1beta1`.

**Comment by grzesuav** [comment]
hi @chenjr0719 , was bit focused on other bug, but it is currently fixed, so it is on my roadmap. Thanks for sharing you discovery, it will debugging easier :)

**Comment by grzesuav** [comment]
https://github.com/metacontroller/metacontroller/pull/293 it is rather user configuration issue, added sections and examples to docs explaining that

**Comment by grzesuav** [comment]
@chenjr0719 please check https://metacontroller.github.io/metacontroller/guide/best-practices.html#working-with-status-subresource-in-metacontroller

**Comment by chenjr0719** [comment]
Thank you a lot @grzesuav . This is very helpful. 👍
