### ISSUE TITLE
Discovery - can metacontroller benefit from building atop of some tooling

### ISSUE THREAD

**Issue by grzesuav** [metacontroller/metacontroller#163]
# Description

There is several options to build controllers in kubernetes :
* kubebuilder - https://github.com/kubernetes-sigs/kubebuilder
* operator-sdk - https://github.com/operator-framework/operator-sdk
*  controller-runtime - https://github.com/kubernetes-sigs/controller-runtime
* crossplane-runtime - https://pkg.go.dev/github.com/crossplane/crossplane-runtime@v0.13.0/pkg/controller

Metacontroler currently does not use any of those, this issue is about discovering if any of those would fit as something which can be adopted to simplify metacontroller architecture etc.

# Actions
* quickly go over each of mentioned frameworks and check if it fits metacontroller.

**Comment by fpetkovski** [comment]
A while back I implemented a metacontroller for TTL controllers using controller-runtime alone and found it to be fully sufficient. A lot of the object watching and controller management boilerplate was done by the library itself. The code can be found here: https://github.com/fpetkovski/k8s-ttl-operator/. I hope it will be useful in making the decision.

**Comment by grzesuav** [comment]
thanks:) , will take a look. I know metacontroller use case is specific (as it is "generic" controller) but I believe it can be simplified

**Comment by fpetkovski** [comment]
I just saw that there is also now [crossplane-runtime](https://pkg.go.dev/github.com/crossplane/crossplane-runtime@v0.13.0/pkg/controller) from the [Crossplane](https://crossplane.io/docs/v1.1/) project. It seems to be more suitable for dynamically spinning up and tearing down controllers.

**Comment by grzesuav** [comment]
thanks for hint @fpetkovski  :) . Adding to the list

**Comment by fpetkovski** [comment]
I created a PR which demonstrates how controller-runtime would help for reducing the codebase of the project. So far it is scoped to the two top-level controllers (decorator and composite). The dynamic ones are not touched. I would be happy to get any feedback on it.

**Comment by grzesuav** [comment]
also found https://github.com/kubernetes-sigs/controller-tools , need to check whats is in there

**Comment by grzesuav** [comment]
Implemented in https://github.com/metacontroller/metacontroller/pull/221 at least first step. Closing.
