### ISSUE TITLE
Enhancement: Emit kubernetes events  

### ISSUE THREAD

**Issue by grzesuav** [metacontroller/metacontroller#170]
# Description
When handling resources, emit events to record what happened (i.e. sync started, sync failed, webhook execution failed etc). It will allow users find out in easy way what is happening with their resources without necessity to check `metacontroller` logs.

# Scope
* add api (in metacontroller codebase) which allow to attach event to particular resource
* should cover wast range of kubernetes versions

**Out of scope**
* not required to add event in all places in metacontroller sourcecode, can be done later
* it is not about allowing third party controllers to add events when their processing `sync`/`customize`/`finalize` webhooks

Related issues : https://github.com/GoogleCloudPlatform/metacontroller/issues/7,

**Comment by grzesuav** [comment]
https://github.com/kubernetes/client-go/tree/v0.17.17/tools/events - package which can be used to implement

**Comment by grzesuav** [comment]
Initial PR - https://github.com/metacontroller/metacontroller/pull/216/

**Comment by sathieu** [comment]
It would be great to allow adding events from third-party controllers too.

**Comment by grzesuav** [comment]
@sathieu I will create another issue for that, as it requires a bit of design about API

**Comment by grzesuav** [comment]
As for now - adding more events related to errors with particular objects

**Comment by grzesuav** [comment]
Closing, as for now if any event is not emitted please open an issue for specific case. For add it this possibility to API (emit events from user controllers) please see - https://github.com/metacontroller/metacontroller/issues/249
