### ISSUE TITLE
nodejs-server

### ISSUE THREAD

**Issue by gprossliner** [metacontroller/metacontroller#187]
Hi!

Ist https://hub.docker.com/r/metacontroller/nodejs-server still maintained? It seems a rather old image, refering to the old git repo.
If not, what would be the updated example of the catset controller?

Thanks!

**Comment by grzesuav** [comment]
Hi !  So firstly, we have some issues with the catset test (https://github.com/metacontroller/metacontroller/issues/144) , secondly we need to look at this test, the nodejs code is here- https://github.com/metacontroller/metacontroller/tree/master/examples/nodejs. In general we need to see where else this server is used and update it accordingly. 

We are open for contribution for this :)

**Comment by gprossliner** [comment]
Thank you grzesuav!
