### ISSUE TITLE
Migrate to go-modules

### ISSUE THREAD

**Issue by grzesuav** [metacontroller/metacontroller#20]
During my work on running tests I discover that in metac there were migration to `gomodules` done, which  make building app and running unit tests easier, we should implement this.

Also question - how metacontroller package should be named ? I noticed it is `metacontroller.app` - why not simply `metacontroller` ?

**Comment by AmitKumarDas** [comment]
Should these be done once we get a release out that matches the gcp/metacontroller master branch?

**Comment by grzesuav** [comment]
Actually no idea - is this needed to release initial version ? I assume we can release "in old way" and then implement this. 

What advantage do we have when enabling go modules ? Easier build setup ?

**Comment by AmitKumarDas** [comment]
go modules is the only standard way to support manage project dependencies.
All other ways have been deprecated long back.

**Comment by AmitKumarDas** [comment]
>Also question - how metacontroller package should be named ? I noticed it is metacontroller.app - why not simply metacontroller ?

It should be a domain name as per go module conventions. We might want to use `metacontroller.io`

**Comment by grzesuav** [comment]
https://github.com/metacontroller/metacontroller/pull/37
