### ISSUE TITLE
Feature proposal : Switch from shared to standalone model

### ISSUE THREAD

**Issue by grzesuav** [metacontroller/metacontroller#218]
#  Proposal

Original proposal - https://github.com/GoogleCloudPlatform/metacontroller/issues/154

Currently there is is single metacontroller instance in while cluster, which has its downsides. I have proposition, similar to above one, but with minor differences.

I believe the standalone//mixed mode can be beneficial, and actually achievable at the  same time. The only significant change would be adding `labelSelector` to metacontroller, with which it will be started, to pick up CRD's to manage (`Decorator` and `Composite` controllers). 

The only thing which need to change is adding additional parameter to metacontroller cmdline - i.e. `-labelSelector` - which would tell which subset of `Decorator` and `Composite` controllers its interested in managing.

This approach have its drawbacks (i.e. accidental setting the same selectors in two different metacontroller installations) but I think potential gain is bigger than this risk.

### Drawbacks of proposal

1.  Metacontroller fighting over resources - can be caused by two metacontroller instances managing the same CRD

### Benefits of proposal

1. Clean separation of different metacontroller instances, in case of
    - Permissions needed to manage its controllers (they can be limited to what actual operator needs)
    - It will allow to apply a Sidecar pattern - so in pod there is metacontroller pod and operator pod, metacontroller manages only this operator. Because of this all communication can be done via `localhost` - best way from security point of view.
  
2. Allow scaling (in some primitive way, but better then now)

**Comment by janaz** [comment]
I would like to see that feature implemented. Currently, my team is using a custom patch (much simpler than the proposed solution which is more generic) on top of the upstream version to achieve the described outcome

**Comment by rosenhouse** [comment]
Thanks for all your work to take over and improve metacontroller. 

This feature (standalone) is really appealing to me, but I wanted to point out two potential issues with the version of the implementation you’ve suggested above, compared with the original. 

One benefit of the original proposal (to have config files on disk for DecoratorController/CompositeController instead of CRDs), is that metacontroller could then be installed within a single namespace, with limited permissions.

Another benefit is that different namespaces could run different versions of metacontroller (consuming different versions of config) without conflict. 

If you support different controller processes but keep the CRDs shared cluster-wide, then installation still requires cluster-scoped permission. Also it introduces risk related to version mismatch between metacontroller process and the DecoratorController/CompositeController CRDs in the cluster (eg imagine one user upgrades metacontroller and the CRDs, but another user in another namespace is still running the older metacontroller).  Of course it is possible to manage that responsibly, it’s just extra complexity. 

I’ll be happy to have standalone either way, but I wanted to share.

**Comment by grzesuav** [comment]
> This feature (standalone) is really appealing to me, but I wanted to point out two potential issues with the version of the implementation you’ve suggested above, compared with the original.

hi @rosenhouse , thanks for that ! Always welcome to listen to ideas/holes in design,

> One benefit of the original proposal (to have config files on disk for DecoratorController/CompositeController instead of CRDs), is that metacontroller could then be installed within a single namespace, with limited permissions.
> 

The same possibility is with this proposal, you install namespaced-metacontroller in given namespace and allow it to modify only limited scoped of resources, depending on the user operator it manages.

> Another benefit is that different namespaces could run different versions of metacontroller (consuming different versions of config) without conflict.

It should be also possible, I do not see any reason why not.


> 
> If you support different controller processes but keep the CRDs shared cluster-wide, then installation still requires cluster-scoped permission.

Is is true that `Composite/Decorator` controller crds are cluster wide resources and you need to tell (by setting labels on particular CR) which should be taken care by which metacontroller instance. I can imagine that for namespaced-only cases we could potentially introduced namespaced version of  `Composite/Decorator` to allow even more fine-grained access control, in that case everything will be holded in scope of given namespace. In this scenario, all resources created by metacontroller will be also limited to given namespace. It is just a though - I need to figure out if this scenario is worth effort and gives meaningful pros.

> Also it introduces risk related to version mismatch between metacontroller process and the DecoratorController/CompositeController CRDs in the cluster (eg imagine one user upgrades metacontroller and the CRDs, but another user in another namespace is still running the older metacontroller). Of course it is possible to manage that responsibly, it’s just extra complexity.
> 


I would say it isn't a big risk - whole k8s ecosystem is doing that - because of that we have different API versions, which are evolving. This is true that with multiple metacontroller instances they may read `Composite/Decorator` in different versions, but as long all the versions are properly defined in CRD itself (https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/) I do not foresee issues here. I mean it can always happen, definitely CRD's would need be installed separately than particular metacontrollers instances, and contain all version used in cluster, but it can be shipped as single CRD object with all versions defined.




> I’ll be happy to have standalone either way, but I wanted to share.


Also, I am not saying that metacontroller will refuse to allow to be configured via config file - it could be also possible, in addition to configuring via `Composite/Decorator` CR's. It is just for me a bit independent from achieving standalone model via CRD's

**Comment by Bobgy** [comment]
I'd like to second @rosenhouse's arguments.

I maintain an open source project, so I don't know in advance whether our users installed metacontroller or not. Also, to use metacontroller for my specific use-case, it needs some specific permissions.

Therefore, it would be a lot easier for me to redistribute my controllers wrote using metacontroller when it's a fully standalone version -- without CRDs, without any cluster-level resources. That makes it possible for me to redistribute metacontroller based controllers with my open source project with minimal dependencies from user setup.

**Comment by grzesuav** [comment]
hi @Bobgy thanks for your input,

as I wrote, config via config file seems to be independent from the proposal of splitting discovery via CRD's.

I will create separate feature proposal for that, I think in that case metacontroller will ignore `Composite/Decorator` controller and just limit to what is in config file, but it will be clarified there.

**Comment by Bobgy** [comment]
Thank you! Yes, it can be seen as a separate request. The only reason we brought it up here is because this issue seems like the follow up of https://github.com/GoogleCloudPlatform/metacontroller/issues/154. While the change to move from CRD to configmap was in the original issue.

**Comment by grzesuav** [comment]
@rosenhouse @Bobgy fyi : https://github.com/metacontroller/metacontroller/issues/266

**Comment by snuggie12** [comment]
I'm personally for making more CRDs as they are way more user/operator friendly:
- There's no `type` like `Secrets` so if people name things poorly you're stuck running multiple commands to try and figure out the appropriate cm to look at.
- `kubectl explain` is easier than looking through APIs on github
- Easier to do RBAC with since it's not a shared `kind`
- Easier to do validation hooks

**Comment by AmitKumarDas** [comment]
My team has tried two approaches 1/ config based 2/ namespace scoped CRD based on metac (fork of metacontroller). Needless to say config based approach has helped us solve most of our requirements. Namespace scoped CRDs help when business logic is glued to Kubernetes's eventual consistency mechanism (_e.g. if metacontroller resource depends on others CRDs that are not yet available in the cluster_). Config based approach has helped us abstract K8s completely & helped our controllers to run smoothly as explained by @Bobgy & @rosenhouse.

Points raised by @grzesuav w.r.t label selectors are still valid. I believe they might help in building canary style deployment for K8s controllers. It might be worthwhile to think of a new metacontroller CRD if that helps (_esp. given the benefits of composing CRs which also helps a controller to adhere to Single Responsibility Pattern_)

**Comment by rolandkool** [comment]
@grzesuav any progress on this initiative? The shared model is quite risky with regards to upgrades and it would also require, like you described, a huge amount of permissions.

**Comment by grzesuav** [comment]
I was thinking of implementing https://github.com/metacontroller/metacontroller/issues/266 first, which would imply that you can have multiple metacontroller's, each considering just the controller provided in config, thus with restricted rbac. However due to changes in API I haven't yet worked on that, mostly because I had some personal stuff going on, changing the job, work travel etc. I am doing that in my private time. However I started work in are of writing operators so getting experience with golang/controllers every day, which will help :). 

Also, we are open for contributions
