### ISSUE TITLE
Folder structure is not compliant with community standard

### ISSUE THREAD

**Issue by fpetkovski** [metacontroller/metacontroller#228]
The layout of the project is quite unique and does not resemble what is typically found in Golang projects.

A good template to follow is the one described in [golang-standards/project-layout](https://github.com/golang-standards/project-layout). Refactoring to this layout would improve navigation and make it easier for people to get involved and make contributions.

My impression is that the biggest change would be introducing a `pkg` folder which would contain all the modules which can be imported by other projects. In the current state, all go modules are at the same level as other, non-go folders, such as scripts and manifests. This makes it a bit hard to distinguish which folders belong to the application, and which ones contain build files and configuration.

**Comment by grzesuav** [comment]
Fully agree, 

current structure is :
```
.
├── apis
│   └── metacontroller
├── client
│   └── generated
├── controller
│   ├── common
│   ├── composite
│   └── decorator
├── docs
│   ├── book
│   └── src
├── dynamic
│   ├── apply
│   ├── clientset
│   ├── controllerref
│   ├── discovery
│   ├── informer
│   └── object
├── events
├── examples
│   ├── bluegreen
│   ├── catset
│   ├── clusteredparent
│   ├── configmappropagation
│   ├── crd-roles
│   ├── daemonjob
│   ├── globalconfigmap
│   ├── go
│   ├── indexedjob
│   ├── jsonnetd
│   ├── nodejs
│   ├── secretpropagation
│   ├── service-per-pod
│   └── status
├── hack
├── hooks
├── manifests
│   ├── debug
│   ├── dev
│   └── production
├── options
├── server
├── test
│   └── integration
└── third_party
    └── kubernetes

```


after introducing `pkg`, it would be more or less 
```
.

├── docs
│   ├── book
│   └── src
├── pkg
│   ├── apis
│   ├── client
│   ├── controller
│   ├── events
│   ├── hooks
│   ├── options
│   ├── server
│   └── third_party
├── examples
│   ├── bluegreen
│   ├── catset
│   ├── clusteredparent
│   ├── configmappropagation
│   ├── crd-roles
│   ├── daemonjob
│   ├── globalconfigmap
│   ├── go
│   ├── indexedjob
│   ├── jsonnetd
│   ├── nodejs
│   ├── secretpropagation
│   ├── service-per-pod
│   └── status
├── hack
├── manifests
│   ├── debug
│   ├── dev
│   └── production
├── test
│   └── integration

```

do we need any other directory ?

**Comment by fpetkovski** [comment]
We could also introduce a `cmd/metacontroller` directory that would contain main.go, but I don't think this would make a big difference right now. There's only one main.go for the application and leaving in the root of the project is fine I think. 

I was also thinking that `options/options.go` could be merged into the server package since since they are only used by the server and specific to the server.

**Comment by grzesuav** [comment]
As I checked `cmd` have more sense if there is more than one executable so might be not use case for metacontroller. I would start with `pkg`, but want to wait till other things get merged to avoid unnecessary rebasing

**Comment by grzesuav** [comment]
Implemented
