### ISSUE TITLE
Describe migration from GCP metacontroller

### ISSUE THREAD

**Issue by janaz** [metacontroller/metacontroller#252]
I upgraded Metacontroller from https://github.com/GoogleCloudPlatform/metacontroller to the recent version - v1.5.6 and I noticed problems with finalizing resources that were created with the old version of Metacontroller.

I looked closer at one of the resources that failed to delete and noticed that the new version expects a slightly different finalized string - `metacontroller.io/*` instead of `metacontroller.app/*`

 ```yaml
 finalizers:
  - metacontroller.app/compositecontroller-ecr-repository-e2e-operator
  - metacontroller.io/compositecontroller-ecr-repository-e2e-operator
```

**Comment by adrianmace** [comment]
It looks like it's related to the refactoring that occurred in this commit: https://github.com/metacontroller/metacontroller/commit/899b843e544ef3793e2c223832077423a6680437

**Comment by grzesuav** [comment]
hi @janaz this is true. I will update documentation. In general similar thing needs to be done - https://github.com/AmitKumarDas/metac#differences-from-metacontroller


so sth like 

```shell
kubectl get <comma separated list of your resource types here> --no-headers --all-namespaces | awk '{print $2 " -n " $1}' | xargs -L1 -P 50 -r kubectl patch -p '{"metadata":{"finalizers": [null]}}' --type=merge
```

**Comment by grzesuav** [comment]
https://kubernetes.slack.com/archives/CA0SUPUDP/p1570787333031800

**Comment by grzesuav** [comment]
https://github.com/metacontroller/metacontroller/pull/256
