### ISSUE TITLE
Metacontroller crashes with fatal error: concurrent map writes

### ISSUE THREAD

**Issue by janaz** [metacontroller/metacontroller#259]
I was testing the `client-go-qps` and `client-go-burst` settings and discovered that metacontroller crashes when I set those values to high numbers. I observed that increasing the number of qps makes it more likely for metacontroller to crash.

The error I'm seeing is
```
fatal error: concurrent map writes
```
followed by a long stack trace

I run metacontroller with the following settings 
```
./metacontroller.io \
  -client-config-path ~/.kube/config \
  -client-go-qps=100 \
  -client-go-burst=200 \
  -workers=5 \
  -v=9 \
  -logtostderr \
  -cache-flush-interval 600m \
  -discovery-interval 600m
```

The version I'm using is v1.5.8. I compiled it from the source on my machine that's running macOS v11.3.1.

The logs and stack traces are available here: https://gist.github.com/janaz/f5c4aef332a22ec01eef637f29ed7601

**Comment by grzesuav** [comment]
hi, thanks for reporting, you were testing on local cluster (minikube/kind etc) or production one ? Looking at stack trace it is related to `customize` feature, will try to take a look over weekend.

**Comment by janaz** [comment]
Yes, I was testing on a local cluster - the one bundled into Docker Desktop for Mac

**Comment by grzesuav** [comment]
hi @janaz , it its not secret, can you share configuration which was applied on cluster ? I mean Composite controller definition , customize hook implementation and some CR's deployed there ? 

Looking at https://github.com/metacontroller/metacontroller/blob/master/pkg/controller/common/customize/manager.go#L90 the invocation of subsequent `cache.Add` (which is causing an issue) is not ready for invocation from multiple threads, just wanted to confirm that. In this case adding simple protections there should work, as subsequent executions could use cached value.


stack trace :
```
goroutine 559 [running]:
runtime.throw(0x21ea81f, 0x15)
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/panic.go:1117 +0x72 fp=0xc0004c9420 sp=0xc0004c93f0 pc=0x1038372
runtime.mapassign_faststr(0x209aca0, 0xc0004fa660, 0xc000746cd0, 0xc, 0xc000746cd0)
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/map_faststr.go:291 +0x3d8 fp=0xc0004c9488 sp=0xc0004c9420 pc=0x1015e78
metacontroller.io/pkg/controller/common/customize.CustomizeResponseCache.Add(...)
	/Users/user/go/src/metacontroller.app/pkg/controller/common/customize/cache.go:11
metacontroller.io/pkg/controller/common/customize.(*Manager).GetCustomizeHookResponse(0xc00050e3a0, 0xc000432010, 0x2, 0x2, 0xc000746ce9)
	/Users/user/go/src/metacontroller.app/pkg/controller/common/customize/manager.go:90 +0x19c fp=0xc0004c9508 sp=0xc0004c9488 pc=0x1e2e45c
metacontroller.io/pkg/controller/common/customize.(*Manager).GetRelatedObjects(0xc00050e3a0, 0xc000432010, 0xc00001f290, 0x0, 0x0)
	/Users/user/go/src/metacontroller.app/pkg/controller/common/customize/manager.go:301 +0x2a6 fp=0xc0004c9728 sp=0xc0004c9508 pc=0x1e30826
metacontroller.io/pkg/controller/composite.(*parentController).syncParentObject(0xc00050e300, 0xc000432010, 0x5, 0xc000801b36)
	/Users/user/go/src/metacontroller.app/pkg/controller/composite/controller.go:492 +0x3fa fp=0xc0004c9b58 sp=0xc0004c9728 pc=0x1eba15a
metacontroller.io/pkg/controller/composite.(*parentController).sync(0xc00050e300, 0xc000801b30, 0x12, 0xc000313700, 0x3)
	/Users/user/go/src/metacontroller.app/pkg/controller/composite/controller.go:465 +0x2df fp=0xc0004c9da0 sp=0xc0004c9b58 pc=0x1eb97bf
metacontroller.io/pkg/controller/composite.(*parentController).processNextWorkItem(0xc00050e300, 0xc0003c0200)
	/Users/user/go/src/metacontroller.app/pkg/controller/composite/controller.go:267 +0xf5 fp=0xc0004c9e60 sp
```

**Comment by janaz** [comment]
Hey @grzesuav. Thaanks for looking at this issue. My local setup is just a bunch of some test CRDs.

I captured the output of `kubectl get compositecontrolllers -o yaml` and `kubectl get crds -o yaml`. You can find it here: https://gist.github.com/janaz/567786826d570ec0dc887aba148abba3

**Comment by grzesuav** [comment]
So simple fix would be to make access there synchronized, but I am thinking of smarter worker processing, currently all the workers gets the items from queue - https://github.com/metacontroller/metacontroller/blob/master/pkg/controller/composite/controller.go#L255

which I think is an issue here, i.e. if we have 4 threads and in queue :
1. parent-rev1
2. parent-rev1
3. parent-rev2
4. otherParent
then each worker will take each element from queue (at least up to my understanding, need to test it) while it would be more sensible to sync the same parent in same worker (or at least in order in which they appear in queue, not concurrent)

**Comment by grzesuav** [comment]
anyway need to check how the queue from client-go actually behaves, but this seems like possible cause

**Comment by totycro** [comment]
I'm getting a similar but not the same error message: `fatal error: concurrent map read and map write`

In my case, this happens about every few days. After this message, the metacontroller is crashlooping and restarts a few times, then the problem disappears.
After the error message, there are about 2000 more lines in the log: [metacontroller.log](https://github.com/metacontroller/metacontroller/files/6552187/metacontroller.log)
I'm using the docker container metacontrollerio/metacontroller:v1.5.3

Do you think that this is the same problem?

**Comment by grzesuav** [comment]
hi @totycro , yes, it is the same :
```
May 26th 2021, 22:55:28.527 runtime.throw(0x14ff71f, 0x21)
May 26th 2021, 22:55:28.527 	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc00038d9a8 sp=0xc00038d978 pc=0x436f32
May 26th 2021, 22:55:28.527 	/go/src/metacontroller.io/controller/common/customize/manager.go:74 +0xe9 fp=0xc00038da90 sp=0xc00038da18 pc=0x124f2c9
May 26th 2021, 22:55:28.527 	/go/src/metacontroller.io/controller/common/customize/manager.go:127 +0x47 fp=0xc00038dc70 sp=0xc00038dc48 pc=0x1252747
```

I will provide quick fix over the week (add guard to the map) and in long term look at more smart thread work (i.e. given parent always land on given thread)

**Comment by grzesuav** [comment]
WIP https://github.com/metacontroller/metacontroller/pull/275

**Comment by grzesuav** [comment]
@janaz @totycro please check version 1.5.12

**Comment by totycro** [comment]
Awesome, i've just updated and no crashes so far!
