### ISSUE TITLE
doc: implement metacontroller docs site

### ISSUE THREAD

**Issue by AmitKumarDas** [metacontroller/metacontroller#3]

**Comment by grzesuav** [comment]
As a starting point - github pages ? Do you have any thought which static site generator to use ?

**Comment by AmitKumarDas** [comment]
I like the way this has been built including the style, font, theme etc.
https://github.com/tinkerbell/tinkerbell.org
So its HUGO & other stuff.

**Comment by grzesuav** [comment]
does it allow to generate diagrams (like dot), which can be handy in documentation ? I see it is based on `.md` sources which is good (as they are pretty simple and powerful)

**Comment by grzesuav** [comment]
So the approach would be to have separate repository which will be hosted site ?

**Comment by AmitKumarDas** [comment]
Let the site content be in the same repo as metacontroller

**Comment by grzesuav** [comment]
@AmitKumarDas what do you think of initially build existing docs and host them, and in second step - change to this hugo ?

**Comment by AmitKumarDas** [comment]
@grzesuav you are right. Second step can be delayed.

**Comment by grzesuav** [comment]
Actuall done, docs are on https://metacontroller.github.io/metacontroller/ , @AmitKumarDas if we are good with this issue can be closed
