### ISSUE TITLE
Can't find resource decoratorcontroller  metacontroller v2.0.4 in kubernetes v1.22.0

### ISSUE THREAD

**Issue by nevzatgul** [metacontroller/metacontroller#344]
I want to create service per pod in kubernetes v1.22.  My cluster have multiple shard.
I have created  a cluster with  GoogleCloudPlatform  metacontroller 0.4.0 and  kubernetes v1.21 before. 
After upgrading to kubernetes 1.22, I had to change the versions from v1beta1 to v1.
In order to update version to v1, I had to update metacontroller too. So I decided to update GoogleCloudPlatform  metacontroller 0.4.0 to metacontroller v2.0.4.

When I want to create decoratorcontroller with the yaml files for version v2.0.4  which are published inside examples on your github repository , I get the following error for shard 0.

kubernetes@km1:~$ kubectl describe decoratorcontrollers.metacontroller.k8s.io  shard-0-pod-name-label
..
..
..
Events:
 Type     Reason       Age                   From            Message
  ----     ------       ----                  ----            -------
  Warning  CreateError  16h (x20 over 16h)    metacontroller  Cannot create new controller: can't find resource "pods" in apiVersion "v1"
  Warning  CreateError  27m (x20 over 66m)    metacontroller  Cannot create new controller: can't find resource "pods" in apiVersion "v1"
  Warning  CreateError  62s (x15 over 2m24s)  metacontroller  Cannot create new controller: can't find resource "pods" in apiVersion "v1"

--

kubernetes@km1:~$ kubectl describe decoratorcontrollers.metacontroller.k8s.io  shard-0-service-per-pod
..
..
..
Events:
  Type     Reason       Age                   From            Message
  ----     ------       ----                  ----            -------
  Warning  CreateError  16h (x20 over 16h)    metacontroller  Cannot create new controller: can't find resource "statefulsets" in apiVersion "apps/v1"
  Warning  CreateError  28m (x20 over 66m)    metacontroller  Cannot create new controller: can't find resource "statefulsets" in apiVersion "apps/v1"
  Warning  CreateError  69s (x15 over 2m31s)  metacontroller  Cannot create new controller: can't find resource "statefulsets" in apiVersion "apps/v1"

--

kubernetes@km1:~$ kubectl logs -n metacontroller metacontroller-0

{"level":"error","ts":1630050326.0129108,"logger":"controller-runtime.manager.controller.decorator-metacontroller","msg":"Reconciler error","name":"shard-0-pod-name-label","namespace":"","error":"can't find resource \"pods\" in apiVersion \"v1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214"}
{"level":"Level(-4)","ts":1630050326.0129387,"logger":"decorator","msg":"Sync DecoratorController","name":"shard-0-service-per-pod"}
{"level":"error","ts":1630050326.013003,"logger":"controller-runtime.manager.controller.decorator-metacontroller","msg":"Reconciler error","name":"shard-0-service-per-pod","namespace":"","error":"can't find resource \"statefulsets\" in apiVersion \"apps/v1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214"}

I don't know  why doesn't  it find any statefulsets.

**Comment by grzesuav** [comment]
hi @nevzatgul , this message is often happening at the start onf metacontroller and/or cache sync, it is described there - https://metacontroller.github.io/metacontroller/guide/troubleshooting.html#common-log-messages.

Except log message, does the example did not work ?
