### ISSUE TITLE
Can finalize hook be triggered when pod is deleted ? 

### ISSUE THREAD

**Issue by K-Jean** [metacontroller/metacontroller#361]
I have a service that should be accessible when a pod is in the "Terminating" state.  
For this I use the "publishNotReadyAddresses" on my service.
My problem is that when the pod goes into the "Terminating" state the finalize hook is called and my service is destroyed.

**Comment by grzesuav** [comment]
Hi,

not sure if I understand your use-case - how your operator works ? What does not work as expected ?
