### ISSUE TITLE
metacontroller handling of dynamic apply for multi-value lists fails for service on same port

### ISSUE THREAD

**Issue by nycnewman** [metacontroller/metacontroller#371]
Metacontroller appears to fail to handle a service where two services (different names) use two protocols (TCP and UDP) on same port. knownMergeKey prioritises port over name and this results in 'duplicate errors' being thrown when apply occurs.

Not clear if switching name and port in priority list would cause other errors. Service appears to come up but it appears to cause metacontroller issues when revalidating state of environment.

**Comment by grzesuav** [comment]
hi @nycnewman could you elaborate a bit ? Are you writing you controller and experiencing some unexpected behavior ?

**Comment by nycnewman** [comment]
I'm asking my engineering team to get a better description but as I understand it, the team are using metacontroller to manager a K8s cluster. We deploy a vendor product that by default exposes two services on the same port under different names and using UDP and TCP. When metacontroller comes to compare the as-is against the definition, it doesn't handle arrays well and has a default sort mechanism (using knownMergeKeys) that prioritises port over name. The resulting diff is broken as metacontroller appears merge the two services into one entry. So service comes up but MC throws error later.

**Comment by nycnewman** [comment]
Names changed to protect the innocent

I0920 14:53:42.315370       1 controller.go:455] "Sync" parent_kind="testSystem" object="test-system"
I0920 14:53:42.437142       1 manage_children.go:218] "Reflect diff: a=observed, b=desired" diff="\u00a0\u00a0map[string]interface{}{
\u00a0\u00a0	\"apiVersion\": string(\"v1\"),
\u00a0\u00a0	\"kind\":       string(\"Service\"),
\u00a0\u00a0	\"metadata\":   map[string]interface{}{\"annotations\": map[string]interface{}{\"metacontroller.k8s.io/last-applied-configuration\": string(`{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"labels\":{\"contr`...)}, \"creationTimestamp\": string(\"2021-09-20T09:03:04Z\"), \"labels\": map[string]interface{}{\"controller-uid\": string(\"4e103700-e8ee-4e85-a6a9-0fcdaff43e42\")}, \"managedFields\": []interface{}{map[string]interface{}{\"apiVersion\": string(\"v1\"), \"fieldsType\": string(\"FieldsV1\"), \"fieldsV1\": map[string]interface{}{\"f:metadata\": map[string]interface{}{\"f:annotations\": map[string]interface{}{\".\": map[string]interface{}{}, \"f:metacontroller.k8s.io/last-applied-configuration\": map[string]interface{}{}}, \"f:labels\": map[string]interface{}{\".\": map[string]interface{}{}, \"f:controller-uid\": map[string]interface{}{}}, \"f:ownerReferences\": map[string]interface{}{\".\": map[string]interface{}{}, `k:{\"uid\":\"4e103700-e8ee-4e85-a6a9-0fcdaff43e42\"}`: map[string]interface{}{\".\": map[string]interface{}{}, \"f:apiVersion\": map[string]interface{}{}, \"f:blockOwnerDeletion\": map[string]interface{}{}, \"f:controller\": map[string]interface{}{}, ...}}}, \"f:spec\": map[string]interface{}{\"f:clusterIP\": map[string]interface{}{}, \"f:ports\": map[string]interface{}{\".\": map[string]interface{}{}, `k:{\"port\":18300,\"protocol\":\"TCP\"}`: map[string]interface{}{\".\": map[string]interface{}{}, \"f:name\": map[string]interface{}{}, \"f:port\": map[string]interface{}{}, \"f:protocol\": map[string]interface{}{}, ...}, `k:{\"port\":18301,\"protocol\":\"TCP\"}`: map[string]interface{}{\".\": map[string]interface{}{}, \"f:name\": map[string]interface{}{}, \"f:port\": map[string]interface{}{}, \"f:protocol\": map[string]interface{}{}, ...}, `k:{\"port\":18301,\"protocol\":\"UDP\"}`: map[string]interface{}{\".\": map[string]interface{}{}, \"f:name\": map[string]interface{}{}, \"f:port\": map[string]interface{}{}, \"f:protocol\": map[string]interface{}{}, ...}}, \"f:selector\": map[string]interface{}{\".\": map[string]interface{}{}, \"f:app\": map[string]interface{}{}}, \"f:sessionAffinity\": map[string]interface{}{}, ...}}, \"manager\": string(\"metacontroller\"), ...}}, ...},
\u00a0\u00a0	\"spec\": map[string]interface{}{
\u00a0\u00a0		\"clusterIP\":  string(\"None\"),
\u00a0\u00a0		\"clusterIPs\": []interface{}{string(\"None\")},
\u00a0\u00a0		\"ports\": []interface{}{
\u00a0\u00a0			map[string]interface{}{\"name\": string(\"https-cluster-tcp-18300\"), \"port\": int64(18300), \"protocol\": string(\"TCP\"), \"targetPort\": int64(18300)},
\u00a0\u00a0			map[string]interface{}{
-\u00a0				\"name\":       string(\"https-cluster-tcp-18301\"),
+\u00a0				\"name\":       string(\"cluster-udp-18301\"),
\u00a0\u00a0				\"port\":       int64(18301),
-\u00a0				\"protocol\":   string(\"TCP\"),
+\u00a0				\"protocol\":   string(\"UDP\"),
\u00a0\u00a0				\"targetPort\": int64(18301),
\u00a0\u00a0			},
\u00a0\u00a0			map[string]interface{}{\"name\": string(\"cluster-udp-18301\"), \"port\": int64(18301), \"protocol\": string(\"UDP\"), \"targetPort\": int64(18301)},
\u00a0\u00a0		},
\u00a0\u00a0		\"selector\":        map[string]interface{}{\"app\": string(\"vendor-controller-pod\")},
\u00a0\u00a0		\"sessionAffinity\": string(\"None\"),
\u00a0\u00a0		\"type\":            string(\"ClusterIP\"),
\u00a0\u00a0	},
\u00a0\u00a0	\"status\": map[string]interface{}{\"loadBalancer\": map[string]interface{}{}},
\u00a0\u00a0}
"
I0920 14:53:42.437187       1 manage_children.go:255] "Updating" parent="test-system" child="vendor/vendor-svc-controller" reason="Recreate update strategy selected"
I0920 14:53:42.467483       1 manage_children.go:218] "Reflect diff: a=observed, b=desired" diff="\u00a0\u00a0map[string]interface{}{
\u00a0\u00a0	\"apiVersion\": string(\"apps/v1\"),
\u00a0\u00a0	\"kind\":       string(\"Deployment\"),
\u00a0\u00a0	\"metadata\":   map[string]interface{}{\"annotations\": map[string]interface{}{\"deployment.kubernetes.io/revision\": string(\"1\"), \"metacontroller.k8s.io/last-applied-configuration\": string(`{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"labels\"`...)}, \"creationTimestamp\": string(\"2021-09-20T09:03:01Z\"), \"generation\": int64(1), \"labels\": map[string]interface{}{\"controller-uid\": string(\"4e103700-e8ee-4e85-a6a9-0fcdaff43e42\")}, ...},
\u00a0\u00a0	\"spec\": map[string]interface{}{
\u00a0\u00a0		... // 4 identical entries
\u00a0\u00a0		\"selector\": map[string]interface{}{\"matchLabels\": map[string]interface{}{\"app\": string(\"vendor-controller-pod\")}},
\u00a0\u00a0		\"strategy\": map[string]interface{}{\"rollingUpdate\": map[string]interface{}{\"maxSurge\": int64(1), \"maxUnavailable\": int64(0)}, \"type\": string(\"RollingUpdate\")},
\u00a0\u00a0		\"template\": map[string]interface{}{
\u00a0\u00a0			\"metadata\": map[string]interface{}{\"creationTimestamp\": nil, \"labels\": map[string]interface{}{\"app\": string(\"vendor-controller-pod\")}},
\u00a0\u00a0			\"spec\": map[string]interface{}{
\u00a0\u00a0				\"affinity\": map[string]interface{}{\"podAntiAffinity\": map[string]interface{}{\"preferredDuringSchedulingIgnoredDuringExecution\": []interface{}{map[string]interface{}{\"podAffinityTerm\": map[string]interface{}{\"labelSelector\": map[string]interface{}{\"matchExpressions\": []interface{}{map[string]interface{}{\"key\": string(\"app\"), \"operator\": string(\"In\"), \"values\": []interface{}{string(\"vendor-controller-pod\")}}}}, \"topologyKey\": string(\"kubernetes.io/hostname\")}, \"weight\": int64(100)}}}},
\u00a0\u00a0				\"containers\": []interface{}{
\u00a0\u00a0					map[string]interface{}{
\u00a0\u00a0						... // 7 identical entries
\u00a0\u00a0						\"terminationMessagePath\":   string(\"/dev/termination-log\"),
\u00a0\u00a0						\"terminationMessagePolicy\": string(\"File\"),
\u00a0\u00a0						\"volumeMounts\": []interface{}{
\u00a0\u00a0							map[string]interface{}{
\u00a0\u00a0								\"mountPath\": string(\"/var/vendor\"),
\u00a0\u00a0								\"name\":      string(\"nv-share\"),
+\u00a0								\"readOnly\":  bool(false),
\u00a0\u00a0							},
\u00a0\u00a0							map[string]interface{}{\"mountPath\": string(\"/run/containerd/containerd.sock\"), \"name\": string(\"runtime-sock\"), \"readOnly\": bool(true)},
\u00a0\u00a0							map[string]interface{}{\"mountPath\": string(\"/host/proc\"), \"name\": string(\"proc-vol\"), \"readOnly\": bool(true)},
\u00a0\u00a0							... // 2 identical elements
\u00a0\u00a0						},
\u00a0\u00a0					},
\u00a0\u00a0				},
\u00a0\u00a0				\"dnsPolicy\":     string(\"ClusterFirst\"),
\u00a0\u00a0				\"restartPolicy\": string(\"Always\"),
\u00a0\u00a0				... // 4 identical entries
\u00a0\u00a0			},
\u00a0\u00a0		},
\u00a0\u00a0	},
\u00a0\u00a0	\"status\": map[string]interface{}{\"availableReplicas\": int64(3), \"conditions\": []interface{}{map[string]interface{}{\"lastTransitionTime\": string(\"2021-09-20T09:05:16Z\"), \"lastUpdateTime\": string(\"2021-09-20T09:05:16Z\"), \"message\": string(\"Deployment has minimum availability.\"), \"reason\": string(\"MinimumReplicasAvailable\"), ...}, map[string]interface{}{\"lastTransitionTime\": string(\"2021-09-20T09:03:01Z\"), \"lastUpdateTime\": string(\"2021-09-20T09:05:16Z\"), \"message\": string(`ReplicaSet \"vendor-controller-pod-54d8cd7444\" has successfull`...), \"reason\": string(\"NewReplicaSetAvailable\"), ...}}, \"observedGeneration\": int64(1), \"readyReplicas\": int64(3), ...},
\u00a0\u00a0}
"
I0920 14:53:42.467537       1 manage_children.go:255] "Updating" parent="test-system" child="vendor/vendor-controller-pod" reason="Recreate update strategy selected"
E0920 14:53:42.500208       1 controller.go:270] failed to sync testSystem "test-system": can't reconcile children for testSystem /test-system: Service "vendor-svc-controller" is invalid: [spec.ports[2].name: Duplicate value: "cluster-udp-18301", spec.ports[2]: Duplicate value: core.ServicePort{Name:"", Protocol:"UDP", AppProtocol:(*string)(nil), Port:18301, TargetPort:intstr.IntOrString{Type:0, IntVal:0, StrVal:""}, NodePort:0}]
I0920 14:53:42.514056       1 reflector.go:381] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: forcing resync

**Comment by grzesuav** [comment]
@nycnewman I do not get the whole context from logs, I would need to know what your controller wants to do, can you explain it ?

Also, which version of metacontroller are you using ? As those logs seems a bit buggy, I think I fixed them few versions ago in 2.0.x, can you update your version and then post logs? They should be much clearer

**Comment by grzesuav** [comment]
Please re-open with additional information
