### ISSUE TITLE
Creating Multiple ports in service-per-pod, Not working

### ISSUE THREAD

**Issue by vigneshpalaniappan** [metacontroller/metacontroller#380]
I have created service-per-pod for statefulset, its working for single 80/udp port. but I needed for multiple ports like 80/udp, 30000/tcp...

Please help, how to create multiple ports in service-per-ports

![OvNXX](https://user-images.githubusercontent.com/82667069/136731230-af77f3fb-1dd1-40a4-b38b-9ff610402794.png)

Please provide some examples

**Comment by grzesuav** [comment]
Closing, please re-open with additional input
