### ISSUE TITLE
Decorator sync hook fails: the object has been modified

### ISSUE THREAD

**Issue by srfrnk** [metacontroller/metacontroller#381]
I'm facing a strange issue with the sync hook failing occasionally saying the object has been modified.
The sync hook response contains annotations and attachments.
I suspect the annotaiont that may be either new or with a new value might be the culprits...
Is it possible the reconciliation mechanism can't handle that?

```json
{
  "level": "error",
  "ts": 1634195532.7002673,
  "msg": "failed to sync XXXXX 'XXXXX': can't update XXXXX XXXXX: Operation cannot be fulfilled on XXXXX: the object has been modified; please apply your changes to the latest version and try again\n",
  "stacktrace": "metacontroller/pkg/controller/decorator.(*decoratorController).worker\n\t/go/src/metacontroller/pkg/controller/decorator/controller.go:293\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:90\nmetacontroller/pkg/controller/decorator.(*decoratorController).Start.func1.1\n\t/go/src/metacontroller/pkg/controller/decorator/controller.go:267"
}
```

**Comment by ipleten** [comment]
I've also seen this with service-per-pod example.

**Comment by grzesuav** [comment]
hi @srfrnk , wil ltry to get over it today

What is your value for `discovery-interval` ? https://metacontroller.github.io/metacontroller/guide/configuration.html

**Comment by srfrnk** [comment]
Thanks @grzesuav.
I have not changed the `discovery-interval` configuration value. I think that means it uses the default which is 30s - am I wrong?
I also suspect it's the frequency however in this use-case a 10 min update would not be possible. The syncs have to be made around 30 secs apart at most to prevent stale code being left in the cluster.
Regarding the question about the `Job` termination... it is most likely it doesn't complete before the next sync - as some jobs e.g. building images may take even minutes. However I think this should not be relevant to this issue as it seems the issue is just with the time based annotation itself rather than anything else. So when I keep the same code only remove the timestamp annotation - it works without any of these warning messages.
WDYT?

**Comment by mjsmith1028** [comment]
Hi @srfrnk does this happen for you on the latest version of metacontroller? I was seeing similar messages when the k8s objects were updated outside of the scope of metacontroller so the resourceVersion changed causing the conflict. https://github.com/metacontroller/metacontroller/pull/376 should fix this scenario.

**Comment by srfrnk** [comment]
Thanks @mjsmith1028 - I'll test it again - I am using the latest but I changed my code to workaround this issue so I'll need to re introduce the old code to test it. Will update here.

**Comment by srfrnk** [comment]
Seems like this has been resolved. Thanks @mjsmith1028! I'll close this issue now.
