### ISSUE TITLE
in v0.4.2 tagged release the manifest still refers to v0.4.1 container image

### ISSUE THREAD

**Issue by nickytd** [metacontroller/metacontroller#39]
Hi
Please update the container image tag in v.0.4.2 as it still  points to the debian bases based distro

Thanks
Niki Dokovski

**Comment by grzesuav** [comment]
hi @nickytd , thanks for reporting, the issue is casued because our githu actions does not replace it, not sure if it can be done in automatic way, will try to tackle that

**Comment by grzesuav** [comment]
https://github.com/metacontroller/metacontroller/issues/25

**Comment by grzesuav** [comment]
Closing as duplicate of https://github.com/metacontroller/metacontroller/issues/25
