### ISSUE TITLE
Broken release while release is building image

### ISSUE THREAD

**Issue by srfrnk** [metacontroller/metacontroller#398]
The [documentation recommends installing](https://metacontroller.github.io/metacontroller/guide/install.html#install-metacontroller-using-kustomize) using:
```bash
kubectl apply -k https://github.com/metacontroller/metacontroller/manifests/production
```
Which means if a new version for https://github.com/metacontroller/metacontroller/manifests/production is pushed it will reference an image that is yet not built.
While CI/CD pipeline will be building it it means installations will be failing.
![Screenshot from 2021-11-25 13-20-00](https://user-images.githubusercontent.com/1501654/143450618-30a5218a-246e-4d80-86f0-474671fd4361.png)

It might be better to push the manifest file as a release artifact and creating a dependecy in the pipeline so that an existing release always refers to an existing image.

**Comment by grzesuav** [comment]
yes, this can happen. 

Docker release process is triggered by `tag` creation, so first branch is created which refers to new version and in the same time build job is triggered, which takes up to 20/25 minutes. Releasing artifacts does not makes the situation better, as release artifacts are created in the same time as `tag`, so they refers image which can be `in progress`.

**Comment by grzesuav** [comment]
need to think if this can be improved, and how.

**Comment by srfrnk** [comment]
First, if it was an artifact I could've used a previous release right now.
Second, it took around 36 mins [this time](https://github.com/metacontroller/metacontroller/runs/4324075143?check_suite_focus=true)
Also - if the manifests artifact is uploaded **after** image creation in the pipeline what you saying will be prevented.

**Comment by srfrnk** [comment]
Example - see this: https://github.com/srfrnk/grafana-dashboard-operator/blob/main/.github/workflows/push.yml

**Comment by grzesuav** [comment]
>  Also - if the manifests artifact is uploaded **after** image creation in the pipeline what you saying will be prevented.

yes, but uploading the artifacts is made by semantic-release step, the same which is deciding if release should be triggered and what version should it have - it is running on master.

Docker build is running after tag creation, so version is calculated and taken from tag, as I need to know if docker images should be build and which version it should have (according to semantic versioning). Will see if it can be improved, I am also open for contributions.

**Comment by grzesuav** [comment]
I will have in mind updating the documentation

**Comment by srfrnk** [comment]
I've created a fork to try an idea...
First - pullling the image build into the main pipeline allows using it as a dependency to make sure the image is built before the release is setup.
Secons createing an artifact in the release [based on this](https://github.com/semantic-release/semantic-release/issues/746)
Still in progress but you can check it [here](https://github.com/srfrnk/metacontroller/tree/issue%23398)
Please LMK what you think about this direction...

**Comment by srfrnk** [comment]
It seems the second part will not work.
Ian se you've already pushed the files as artifacts to the release but they cannot be used from there.
```bash
kubectl apply -k https://github.com/metacontroller/metacontroller/releases/download/v2.0.17                    
error: evalsymlink failure on '/tmp/kustomize-917936906/releases/download/v2.0.17' : lstat /tmp/kustomize-917936906/releases: no such file or directory
```
Any ideas?

**Comment by grzesuav** [comment]
hi, sorry, will try to look over next couple of days, if I am unresponsive please ping me on #metacontroller slack channel, it is easy to miss gihub notification

**Comment by grzesuav** [comment]
I changed release process, now it is using goreleaser and is much faster
