### ISSUE TITLE
create.md: no matches for kind "Deployment" in version "apps/v1beta1"

### ISSUE THREAD

**Issue by danielgazineu** [metacontroller/metacontroller#40]
Following the steps described at https://metacontroller.app/guide/create, I get this error:

```
$ kubectl -n hello apply -f webhook.yaml
error: unable to recognize "webhook.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
```
I changed apiVersion of webkook.yaml to apps/v1 and it worked.

Running on minikube v1.12.3 with kubectl 1.18.8.

**Comment by grzesuav** [comment]
yes, it was removed as deprecated api, @AmitKumarDas we propably should target new k8s releases

**Comment by AmitKumarDas** [comment]
Yes. We will update the docs soon

**Comment by grzesuav** [comment]
@danielgazineu fixed in abovementioned MR, closing.
