### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by oridool** [metacontroller/metacontroller#42]
Hello,
Where can I find helm chart for this project? 
The only one I found is a closed PR in helm/charts : https://github.com/helm/charts/pull/8591/files 
But it doesn't seem to be in their master branch .

Thank you.

**Comment by grzesuav** [comment]
hi @oridool , we do not have one yet

**Comment by sathieu** [comment]
@oridool Please test this PR: https://github.com/metacontroller/metacontroller/pull/299
