### ISSUE TITLE
Release pipeline is invalid

### ISSUE THREAD

**Issue by rouke-broersma** [metacontroller/metacontroller#460]
It seems that the changes to the release pipeline yaml are invalid, which means the container images for 2.2.5 have not been released. See: https://github.com/metacontroller/metacontroller/actions/runs/1875344002

```
[Invalid workflow file: .github/workflows/release-pipeline.yaml#L39](https://github.com/metacontroller/metacontroller/actions/runs/1875344002/workflow)
You have an error in your yaml syntax on line 39
```

**Comment by rouke-broersma** [comment]
I believe the issue is the following:

'Matrix options must only contain primitive values'

I don't think you can use complex types in the matrix options unfortunately.

**Comment by rouke-broersma** [comment]
What you probably want to do here is create a 'custom' github action which servers as a template, which consists of the pipeline steps you want to run, with the matrix data as the input. You can then reference this 'action' with the required inputs 3 times in this pipeline to keep it DRY.

**Comment by rouke-broersma** [comment]
@grzesuav I created an example PR of how this might look.

**Comment by grzesuav** [comment]
hi, yes, was able to fix it https://github.com/metacontroller/metacontroller/pull/461 however was working in between so didn't manage to merge it, now should be fine

**Comment by grzesuav** [comment]
Unfortunately issue was exposed now, when the workflow was triggered, and it was merged two day ago. Linting could be improved on gihub side

**Comment by grzesuav** [comment]
@rouke-broersma thanks, for now I will stick to regular action matrix

**Comment by rouke-broersma** [comment]
> @rouke-broersma thanks, for now I will stick to regular action matrix

That's fine
