### ISSUE TITLE
Metacontroller Looping Updates: DecoratorController Looping with Child Updates

### ISSUE THREAD

**Issue by jeleesf** [metacontroller/metacontroller#472]
Hi all,

I have created a DecoratorController to target Istio Gateway objects and attach a new Kubernetes secret. This is working, however I am running into an issue where the Metacontroller continuously sends the attachment of the Kubernetes secret as an update to the DecoratorController creating a loop of continuous updates. The secret values themselves are the same. Looking into other people who have had this issue, the remedy seemed to be adding `subresouces: status: {}` however this was for CRDs that were defined. I am not using this, just using Istio's regular Gateway object which doesn't have this field... 
Any suggestions or help on this issue? Thanks

**Comment by grzesuav** [comment]
@jeleesf could you check by `get crd` istio gateway ? I guess they should have this added, but best to make sure

**Comment by grzesuav** [comment]
@jeleesf also, what do you see in logs as a reason for update ? What you can see in `patch Diff` ?

**Comment by grzesuav** [comment]
no user input, please re-open with additional informations
