### ISSUE TITLE
Use create instead of apply for secrets

### ISSUE THREAD

**Issue by natalian98** [metacontroller/metacontroller#523]
Metacontroller uses `kubectl apply` to create secrets. That adds an annotation with the last applied configuration. Due to that, any secret keys are visible in plain text when using `kubectl describe`.
The issue was also raised [on k8s repo](https://github.com/kubernetes/kubernetes/issues/23564) and it was stated that `kubectl create` and `patch` should be used instead of `apply` for secrets.

**Comment by grzesuav** [comment]
hi, thanks for reporting. Metacontroller does not use `kubectl apply`, but use the same semantic and add a `last-applied-configuration` to keep last applied value.

**Comment by grzesuav** [comment]
And what is there is required as metacontroller need to calculate diff-merge based on that

**Comment by grzesuav** [comment]
Hmm need to check RBAC model, but does user can actually perform `describe` without read access to secret ?

**Comment by natalian98** [comment]
Thanks a lot for your answer, it's much appreciated.
Having tested the rbac model, it looks that a role with `describe` access only doesn't work - it can be created, but will not grant any kind of access.
If a role with `get` access-only is created, the secret can be described as well.
As having read access with `get` enables to get the secret in yaml and use `edit` (without permission to actually patch the resource, but it can still be viewed), the annotation shouldn't be considered as a security issue.
