### ISSUE TITLE
Feature request - Support for rate limiting (HTTP 429)

### ISSUE THREAD

**Issue by adrianmace** [metacontroller/metacontroller#533]
## Summary

Our sync hook sends 429 responses back to Metacontroller when it is overloaded - in an effort to mitigate 3rd party API limits being exceeded - but it doesn't seem like Metacontroller is honouring it.

## Request

Could we please see that HTTP 429 responses are correctly handled? This should also include support for the [`Retry-After`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) header (which we set in attempt to control back-off).

## Example Error Log Entry

(Do note that we have forked metacontroller internally and modified the source to meet certain security desires, so the line numbers represented here may not be exact.)

```
{"level":"error","ts":1653018362.3708982,"msg":"failed to sync CUSTOM_RESOURCE 'NAMESPACE/METADATA_NAME': sync hook failed for CUSTOM_RESOURCE NAMESPACE/METADATA_NAME: sync hook failed: remote error: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>429 Too Many Requests</title>\n<h1>Too Many Requests</h1>\n<p>Rate Limit exceeded: 1 per 1 second</p>\n","stacktrace":"metacontroller/pkg/controller/composite.(*parentController).worker\n\t/go/src/metacontroller/pkg/controller/composite/controller.go:286\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:90\nmetacontroller/pkg/controller/composite.(*parentController).Start.func1.1\n\t/go/src/metacontroller/pkg/controller/composite/controller.go:262"}
```

**Comment by grzesuav** [comment]
hi @adrianmace , it is a reasonable request. However I need to think how to implement it. It most probably will be spread across the code. 

Also, need to consider where to store information about how long to wait etc.

**Comment by grzesuav** [comment]
from other point, what features re. security are missing in metacontroller ?

**Comment by adrianmace** [comment]
Rather than run a single global instance of Metacontroller, we run one instance per CompositeController following the principle of least privilege for each one when it comes to the RBAC. We forked it to introduce filtering via environment variables so metacontroller would only watch the kinds we specify.

The other reason we maintain a fork is so that we can inject the AWS IAM Authenticator into the container. We run metacontroller in ECS rather than EKS, which means we are using IAM role to authenticate.

**Comment by grzesuav** [comment]
got it, so I guess https://github.com/metacontroller/metacontroller/issues/266 would address first concern
