### ISSUE TITLE
Publish ARM64 image

### ISSUE THREAD

**Issue by jerrinot** [metacontroller/metacontroller#55]
Please publish ARM64 container image. The current image supports AMD64 only.
Thank you!

**Comment by grzesuav** [comment]
Doable, we would need to have pipeline specific for ARM, but should be done. If anyone can share some best practices how to do it with github actions please put suggestion to this issue

**Comment by grzesuav** [comment]
hi @jerrinot , can you check on ARM device one of https://hub.docker.com/repository/docker/metacontrollerio/metacontroller/tags?page=1&ordering=last_updated&name=v1.2.1 ?

**Comment by grzesuav** [comment]
I tested image with docker on rpi4 - seems to work. Closing issue
