### ISSUE TITLE
Generate desired state once

### ISSUE THREAD

**Issue by karlschriek** [metacontroller/metacontroller#556]
I am trying to put together a CompositeController that needs to generate certain unique values that go into the desired state. These values should only be generated _once_, so I need some way of having them remembered. Are far as I can tell, the CompositeController (and possibly others as well; I have not worked with them before) works by recalculating the desired state every time the webhook is called and sending that back the "status" (in order to update the parent) and and "children" (i.e. the desired state).

So if the psuedo-code for the (python-based) sync function looks like this:
```
def sync(self, parent, children):
    # calculate current status
    ....

    # calculate desired state
    replicas = parent.get("spec").get("replicas")
    namespace = parent.get("metadata", {}).get("namespace")
    address = generate_address() # This generates a unique value
    desired_resources = build_desired(parent.get("spec"), namespace, address) # This generates the desired resource specs

    return {"status": current_status, "children": desired_resources}

```

What I need is a way to remember that "address" has already been calculated. (This is a simplification, the actual generation steps are much more complicated). Is there some way that the CompositeController can support this case? Can I for example access the previously declared `"children": desired_resources`?

I would like to avoid having to keep a local cache on the webhook server. If I can get the _previous_ result of `"children"` back, plus I can get the _previous_ parent then I could implement simple logic like:

```python
if parent == previous_parent:
  desired_resources = previous_desire_resources
else
  desired_resources = build_desired(...)
```

Is there some way to do this? Would I for example be able to rely on the annotation `metacontroller.k8s.io/last-applied-configuration` always having the correct latest information? In that case I could reconstruct it as:

```python
def get_latest_applied_resources(children):
    latest_applied_resources = []

    for d in children.values():
        for child in d.values():
            latest_applied_resources.append(
                json.loads(
                    child.get("metadata", {})
                    .get("annotations", {})
                    .get("metacontroller.k8s.io/last-applied-configuration")
                )
            )

    return latest_applied_resources
```

This does work, but I do not know if this can be used with confidence. Is it possible that the webhook is called again before all of the children have been updated? What happens if apply fails for some?

For parent the issue is altogether different, since there is only  `kubectl.kubernetes.io/last-applied-configuration` which gets when applying the CR, so by the time it gets to the webhook, the _previous_ last-applied is no longer available.

**Comment by grzesuav** [comment]
Closing as no additional input. Feel free to reopen with additional comments.
