### ISSUE TITLE
Make webhook support caching via etag

### ISSUE THREAD

**Issue by dkropachev** [metacontroller/metacontroller#558]
In order to reduce traffic between webhook server and metacontroller it worth to implement content caching.
With given implementation, i.e. POST methods, most suitable mechanism would he [eTagging](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag).

How it should work:
- eTag - a content hash that is supposed to be calculated of the content.
- It is getting exposed as a http header when webhook server responds to the client
- If client supports eTagging on next try it should send etag value of the content it cached as value of "If-None-Match" header.
- When webhook server sees this header and supports eTagging, it should send 304 "Unmodified" response with empty body if content (i.e. eTag) have not changed.
- Otherwise it sends full response as usual

**Comment by grzesuav** [comment]
https://github.com/metacontroller/metacontroller/pull/557

**Comment by grzesuav** [comment]
Merged
