### ISSUE TITLE
[Feature request] Allow configuration of customize response cache defaultExpiration and cleanupInterval

### ISSUE THREAD

**Issue by mikesmithgh** [metacontroller/metacontroller#560]
This is a feature request to expose `defaultExpiration` and `cleanupInterval` parameters of the customize cache such that they can be configured on metacontroller startup. Most likely as command line arguments (https://github.com/metacontroller/metacontroller/blob/master/main.go#L42).

Metacontroller currently caches the response from customize webhook calls with `defaultExpiration` of 20 min and `cleanupInterval` of 10 min. See https://github.com/metacontroller/metacontroller/blob/af5d9e773fffa9183f081434fcbdc6e336c03e0d/pkg/controller/common/customize/cache.go#L36 and https://github.com/arp242/zcache/blob/v1.2.0/zcache.go#L694

The goal is to allow the user to determine the tradeoffs between memory consumption/webhook calls and allow them to configure the cache as they see fit.

**Comment by newtondev** [comment]
@mikesmithgh I would like to pick this one up. Happy to discuss further on Slack.

**Comment by newtondev** [comment]
@grzesuav this seems to already have been worked on and this ticket is old and can be closed?

See: https://github.com/metacontroller/metacontroller/blob/master/pkg/hooks/webhook.go#L87 and https://github.com/metacontroller/metacontroller/blob/master/pkg/hooks/webhook.go#L90

**Comment by grzesuav** [comment]
ah, then closing
