### ISSUE TITLE
Customize hook accepts incorrect labelSelector format

### ISSUE THREAD

**Issue by rolandkool** [metacontroller/metacontroller#572]
The customize hook can return a list of related resources that are required for the sync hook.
Resources can be filtered using a labelSelector, however when the labelSelector is of the wrong format, the labelSelector basically becomes empty, but no warning or error is logged by the metacontroller.

Would be nice if an incorrect labelSelector would throw an error describing what is wrong. Alternatively, the docs could be updated to provide some examples.

**Comment by grzesuav** [comment]
After searching, it seems it is default behavior - https://pkg.go.dev/encoding/json#Unmarshal . Actually metacontroller is using `kubernetes` wrapper around the standard `json` package, need to check if the behavior can be easily adjusted

**Comment by grzesuav** [comment]
@rolandkool I could potentially expose option `useStrictJsonDecoding` to configure this behavior. WDYT ?
