### ISSUE TITLE
Migrate initial code base from GoogleCloudPlatform/metacontroller

### ISSUE THREAD

**Issue by alaimo** [metacontroller/metacontroller#6]
Migrate the master branch from GoogleCloudPlatform/metacontroller to metacontroller/metacontoller where it will be actively maintained. Work with GCP to archive GoogleCloudPlatform/metacontroller with a redirection notice that instructs users towards the new repository.

**Comment by alaimo** [comment]
GoogleCloudPlatform/metacontroller has been mirrored to metacontroller/metacontoller.

**Comment by AmitKumarDas** [comment]
Closing this issue since this has been achieved
