### ISSUE TITLE
[Feature request] Default update strategy

### ISSUE THREAD

**Issue by zefir01** [metacontroller/metacontroller#664]
Hello.

If I don't specify the GVK of the children, then the default policy is OnDelete, which means I can't change the state of the created children. This makes it difficult to make more dynamic controllers.

I need a function that allows you to specify a default strategy for children, without explicitly specifying their list. This will allow you to make much more dynamic code.

I created a PR where this is implemented. If no default policy is specified, then the current algorithm remains virtually unchanged. This gives full backwards compatibility.

https://github.com/metacontroller/metacontroller/pull/662

**Comment by grzesuav** [comment]
hi @zefir01, GVK of children is required, not sure what you want to achieve. Please elaborate on that with some use case

**Comment by zefir01** [comment]
I want to be able to make more complex controllers where it is not known in advance which children will be created.

Now I'm making a framework that makes it more convenient to work with crossplane. and I need this feature. the main idea is to make it as simple as teraform by taking care of all the CRD and controller work.

**Comment by grzesuav** [comment]
Close as no plan to implement
