### ISSUE TITLE
Allow to set custom ca cert

### ISSUE THREAD

**Issue by grzesuav** [metacontroller/metacontroller#67]
Allow to set custom ca file, in general it is about porting https://github.com/GoogleCloudPlatform/metacontroller/pull/50/ to this repo

**Comment by grzesuav** [comment]
I looked at implementation there, main difference is that back then there was just one http client, and currently there is configuration per controller (each controller have separate `webhook` configuration - https://metacontroller.github.io/metacontroller/api/hook.html#webhook) and sensible is to add there `ca--bundle-path` element which, if provided, will be used to create client for this particular controller.


About api change - it would be adding field, defaulting to empty one, with path, where metacontroller (when run) should look for ca-cert. 



@AmitKumarDas @bsherrod @bakins any opinion on that proposal ?

**Comment by MartinKanters** [comment]
Are there ideas for implementing this? I'm in need of this as well.

**Comment by grzesuav** [comment]
hi, original implementation was made much earlier, so it does not fit to current design, I will edit issue to propose some API change (should be not breaking)

**Comment by MartinKanters** [comment]
@grzesuav Alright, thanks! Looking forward to it :)

**Comment by grzesuav** [comment]
Closing in favor of https://github.com/metacontroller/metacontroller/issues/255
