### ISSUE TITLE
Error when /status subresource is not enabled

### ISSUE THREAD

**Issue by grzesuav** [metacontroller/metacontroller#68]
Originates https://github.com/GoogleCloudPlatform/metacontroller/issues/176

More context here https://stackoverflow.com/questions/56427423/metacontroller-how-to-stop-calls-to-sync-hooks-and-resource-generation/

**Comment by grzesuav** [comment]
https://github.com/GoogleCloudPlatform/metacontroller/issues/197

**Comment by mikebryant** [comment]
Are there any circumstances where the status subresource can't be enabled?

Should it be an error rather than a warning - so people will get early warning their CRD needs changing when they first start testing, and a clear message of how to fix it?

**Comment by grzesuav** [comment]
Yes, it should be an error, with a message explaining how to fix that

**Comment by grzesuav** [comment]
Also I think metacontroller should ignore given resource until fixed as it will cause malfunction

**Comment by grzesuav** [comment]
https://github.com/metacontroller/metacontroller/pull/226
