### ISSUE TITLE
Migration of cutomize hook implementation

### ISSUE THREAD

**Issue by grzesuav** [metacontroller/metacontroller#69]
Migrate and review https://github.com/GoogleCloudPlatform/metacontroller/pull/168 , which is implementation of https://metacontroller.github.io/metacontroller/design/customize-hook.html

**Comment by grzesuav** [comment]
https://github.com/GoogleCloudPlatform/metacontroller/issues/98

**Comment by grzesuav** [comment]
cc: original authors @mikebryant and @Kritzefitz (original authors) to be aware

**Comment by mikebryant** [comment]
I don't have time to come poke at this right now, but I hope you manage to make use of the code :)

**Comment by grzesuav** [comment]
I hope so ;) will se, hopefully either me or anyone else can pick it up soon

**Comment by grzesuav** [comment]
Adjustment attempt - https://github.com/metacontroller/metacontroller/pull/145
