### ISSUE TITLE
Crash / nil pointer dereference (maybe because there is only a finalize webhook, and not a sync webhook)?

### ISSUE THREAD

**Issue by EmielBruijntjes** [metacontroller/metacontroller#702]
Hi,

I don't know if the following stacktrace/log is useful, but we experienced a crash. What *might* be related is that we set up a CompositeController with **only** a finalize webhook, and **no** sync webhook ("Why did you do that?" you might ask. Well, we were phasing out a certain webhook, but still had resources that referred to it via the "finalizer" property, so we decided to leave the finalize webhook around for a while, and only remove the 'sync' webhook. Not sure though if this is indeed the cause of this crash.

See below for the info from the log:

```
{"level":"error","ts":1667418567.4376738,"msg":"Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)\ngoroutine 747 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x1545100?, 0x242b0f0})\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/runtime/runtime.go:75 +0x99\nk8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc002fe6d70?})\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/runtime/runtime.go:49 +0x75\npanic({0x1545100, 0x242b0f0})\n\t/opt/hostedtoolcache/go/1.19.1/x64/src/runtime/panic.go:884 +0x212\nmetacontroller/pkg/hooks.(*hookExecutorImpl).Call(0xc0028a8b98?, {0x1948720?, 0xc006751c80?}, {0x147eb80?, 0xc006751cb0?})\n\t/home/runner/work/metacontroller/metacontroller/pkg/hooks/hooks.go:60 +0x2f\nmetacontroller/pkg/controller/composite.(*parentController).callHook(0xc000158700, 0xc0028a8b98, 0xc006751c20, 0xc006751c50)\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/hooks.go:51 +0x1f6\nmetacontroller/pkg/controller/composite.(*parentController).syncRevisions(0xc000158700, 0xc0028a8b98, 0xc006751c20, 0x451b92?)\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller_revision.go:86 +0x1bc\nmetacontroller/pkg/controller/composite.(*parentController).syncParentObject(0xc000158700, 0xc0028a8b98)\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:529 +0x32e\nmetacontroller/pkg/controller/composite.(*parentController).sync(0xc000158700, {0xc006a6b830?, 0x0?})\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:494 +0x385\nmetacontroller/pkg/controller/composite.(*parentController).processNextWorkItem(0xc000158700)\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:296 +0x105\nmetacontroller/pkg/controller/composite.(*parentController).worker(0xc002618e98?)\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:285 +0x25\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:157 +0x3e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x46ad59?, {0x1948380, 0xc006751b00}, 0x1, 0xc001732180)\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:158 +0xb6\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0x100000000?, 0x3b9aca00, 0x0, 0x10?, 0xc00240dacc?)\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:135 +0x89\nk8s.io/apimachinery/pkg/util/wait.Until(...)\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:92\nmetacontroller/pkg/controller/composite.(*parentController).Start.func1.1()\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:261 +0x89\ncreated by metacontroller/pkg/controller/composite.(*parentController).Start.func1\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:259 +0x85f\n","stacktrace":"k8s.io/apimachinery/pkg/util/runtime.logPanic\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/runtime/runtime.go:79\nk8s.io/apimachinery/pkg/util/runtime.HandleCrash\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/runtime/runtime.go:49\nruntime.gopanic\n\t/opt/hostedtoolcache/go/1.19.1/x64/src/runtime/panic.go:884\nruntime.panicmem\n\t/opt/hostedtoolcache/go/1.19.1/x64/src/runtime/panic.go:260\nruntime.sigpanic\n\t/opt/hostedtoolcache/go/1.19.1/x64/src/runtime/signal_unix.go:835\nmetacontroller/pkg/hooks.(*hookExecutorImpl).Call\n\t/home/runner/work/metacontroller/metacontroller/pkg/hooks/hooks.go:60\nmetacontroller/pkg/controller/composite.(*parentController).callHook\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/hooks.go:51\nmetacontroller/pkg/controller/composite.(*parentController).syncRevisions\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller_revision.go:86\nmetacontroller/pkg/controller/composite.(*parentController).syncParentObject\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:529\nmetacontroller/pkg/controller/composite.(*parentController).sync\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:494\nmetacontroller/pkg/controller/composite.(*parentController).processNextWorkItem\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:296\nmetacontroller/pkg/controller/composite.(*parentController).worker\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:285\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:157\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:135\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:92\nmetacontroller/pkg/controller/composite.(*parentController).Start.func1.1\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:261"}
```

**Comment by grzesuav** [comment]
`{"level":"error","ts":1667418567.4376738,"msg":"Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)\ngoroutine 747 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x1545100?, 0x242b0f0})\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/runtime/runtime.go:75 +0x99\nk8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc002fe6d70?})\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/runtime/runtime.go:49 +0x75\npanic({0x1545100, 0x242b0f0})\n\t/opt/hostedtoolcache/go/1.19.1/x64/src/runtime/panic.go:884 +0x212\nmetacontroller/pkg/hooks.(*hookExecutorImpl).Call(0xc0028a8b98?, {0x1948720?, 0xc006751c80?}, {0x147eb80?, 0xc006751cb0?})\n\t/home/runner/work/metacontroller/metacontroller/pkg/hooks/hooks.go:60 +0x2f\nmetacontroller/pkg/controller/composite.(*parentController).callHook(0xc000158700, 0xc0028a8b98, 0xc006751c20, 0xc006751c50)\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/hooks.go:51 +0x1f6\nmetacontroller/pkg/controller/composite.(*parentController).syncRevisions(0xc000158700, 0xc0028a8b98, 0xc006751c20, 0x451b92?)\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller_revision.go:86 +0x1bc\nmetacontroller/pkg/controller/composite.(*parentController).syncParentObject(0xc000158700, 0xc0028a8b98)\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:529 +0x32e\nmetacontroller/pkg/controller/composite.(*parentController).sync(0xc000158700, {0xc006a6b830?, 0x0?})\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:494 +0x385\nmetacontroller/pkg/controller/composite.(*parentController).processNextWorkItem(0xc000158700)\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:296 +0x105\nmetacontroller/pkg/controller/composite.(*parentController).worker(0xc002618e98?)\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:285 +0x25\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:157 +0x3e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x46ad59?, {0x1948380, 0xc006751b00}, 0x1, 0xc001732180)\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:158 +0xb6\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0x100000000?, 0x3b9aca00, 0x0, 0x10?, 0xc00240dacc?)\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:135 +0x89\nk8s.io/apimachinery/pkg/util/wait.Until(...)\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:92\nmetacontroller/pkg/controller/composite.(*parentController).Start.func1.1()\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:261 +0x89\ncreated by metacontroller/pkg/controller/composite.(*parentController).Start.func1\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:259 +0x85f\n","stacktrace":"k8s.io/apimachinery/pkg/util/runtime.logPanic\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/runtime/runtime.go:79\nk8s.io/apimachinery/pkg/util/runtime.HandleCrash\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/runtime/runtime.go:49\nruntime.gopanic\n\t/opt/hostedtoolcache/go/1.19.1/x64/src/runtime/panic.go:884\nruntime.panicmem\n\t/opt/hostedtoolcache/go/1.19.1/x64/src/runtime/panic.go:260\nruntime.sigpanic\n\t/opt/hostedtoolcache/go/1.19.1/x64/src/runtime/signal_unix.go:835\nmetacontroller/pkg/hooks.(*hookExecutorImpl).Call\n\t/home/runner/work/metacontroller/metacontroller/pkg/hooks/hooks.go:60\nmetacontroller/pkg/controller/composite.(*parentController).callHook\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/hooks.go:51\nmetacontroller/pkg/controller/composite.(*parentController).syncRevisions\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller_revision.go:86\nmetacontroller/pkg/controller/composite.(*parentController).syncParentObject\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:529\nmetacontroller/pkg/controller/composite.(*parentController).sync\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:494\nmetacontroller/pkg/controller/composite.(*parentController).processNextWorkItem\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:296\nmetacontroller/pkg/controller/composite.(*parentController).worker\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:285\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:157\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:135\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:92\nmetacontroller/pkg/controller/composite.(*parentController).Start.func1.1\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/composite/controller.go:261"}`


Thanks, will take a look

**Comment by grzesuav** [comment]
@EmielBruijntjes which version of metacontroller is it ?

**Comment by grzesuav** [comment]
I think I got it, it is because of https://github.com/metacontroller/metacontroller/blob/master/pkg/controller/composite/hooks.go#L54-L59 - when you have finalize webhook only and resource isn't removed it call sync hook

**Comment by EmielBruijntjes** [comment]
Yes that indeed looks like the issue, we had not sync-webhook, just a finalize-webhook because we were terminating that resource.

**Comment by grzesuav** [comment]
@EmielBruijntjes thanks, will think if it can be easily adapted

**Comment by grzesuav** [comment]
@EmielBruijntjes merged the fix
