### ISSUE TITLE
4.7.3 container image not released

### ISSUE THREAD

**Issue by rouke-broersma** [metacontroller/metacontroller#740]
The 4.7.3 chart has been released but the container image has not, so the chart version is not working.
It looks to me like for some reason the tag push workflow was skipped which I guess caused the image workflow to not trigger?

https://github.com/metacontroller/metacontroller/actions/runs/3906273179/jobs/6674787965

**Comment by grzesuav** [comment]
hmm seems this step failed - https://github.com/metacontroller/metacontroller/actions/runs/3906080011/jobs/6674102628

**Comment by grzesuav** [comment]
Added `package.json`, reverten and re-triggered a release
