### ISSUE TITLE
Send hooks as cloudevents

### ISSUE THREAD

**Issue by Shashankft9** [metacontroller/metacontroller#778]
Consider adding a configuration argument while deploying metacontroller, which when set to true, makes metacontroller send the hooks to the endpoint in the format of a cloudevent.
more about cloudevents: https://github.com/cloudevents/spec

This could help with following things:
- when the endpoints are functions (knative, fission etc), they can be written so as to expect a cloudevent in the request body, which can be parsed later on to extract the actual data like you'd do from a http request body (using the cloudevent sdk in go, python etc)
- better integration with eventing frameworks - for example, knative has sources that sends calls to functions/services in the form of cloudevent, with some standardization on metrics, traces and more
- so essentially, metacontroller can also act as a source of events that trigger functions - which it does even now, but this will make it more flavored  (when required) towards the concept of functions and eventing frameworks 

/enhancement

**Comment by grzesuav** [comment]
@Shashankft9 can you elaborate how it should look like in practice ? Not sure how adapting to sending a messages in format like https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#example make is easier/more adaptable for anything

**Comment by grzesuav** [comment]
Closing as no input
