### ISSUE TITLE
Can't Decorate Namespaces with Labels

### ISSUE THREAD

**Issue by wrkode** [metacontroller/metacontroller#792]
I'm trying to build a Decorator that adds a given label `testns = verified` to any Namespace that contains annotation `field.cattle.io/projectId`.
In metacontroller logs I see the request being sent and a response received and as well metacontroller tries to update the namespace as well, but ultimately the label is not added. I've tried with and without passing attachments. I'm not sure what I'm doing wrong here (and I'm still building knowledge on MC):

**decorator.yaml**
`
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: namespace-labeler
spec:
  resources:
  - apiVersion: v1
    resource: namespaces
    annotationSelector:
      matchExpressions:
      - {key: field.cattle.io/projectId, operator: Exists}
  hooks:
    sync:
      webhook:
        url: http://namespace-labeler-service.metacontroller.svc.cluster.local:5000/sync
  attachments:
  - apiVersion: v1
    resource: namespaces
    updateStrategy:
      method: InPlace`
      
      **deployment.yaml**
      `
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-labeler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namespace-labeler
  template:
    metadata:
      labels:
        app: namespace-labeler
    spec:
      containers:
      - name: namespace-labeler
        image: python:3.9-alpine
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "from flask import Flask, request, jsonify
          import json
          import logging
          
          app = Flask(__name__)
          logging.basicConfig(level=logging.DEBUG)
          
          @app.route('/sync', methods=['POST'])
          def sync_hook(request):
              parent = request['object']
              children = request['attachments']
          
              namespace_labels = parent['metadata'].get('labels', {})
              namespace_labels['testns'] = 'verified'
              children['Namespace.v1'] = [{
                  'apiVersion': 'v1',
                  'kind': 'Namespace',
                  'metadata': {
                      'name': parent['metadata']['name'],
                      'labels': namespace_labels
                  }
              }]
          
              response = {
                  "status": {},
                  "attachments": children['Namespace.v1']
              }
          
              return flask.jsonify(response)
          
          if __name__ == '__main__':
              app.run(host='0.0.0.0', port=5000)" > /app/sync.py;
          pip install flask;
          python /app/sync.py
        volumeMounts:
        - name: app
          mountPath: /app
        ports:
        - containerPort: 5000
      volumes:
      - name: app
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: namespace-labeler-service
spec:
  selector:
    app: namespace-labeler
  ports:
    - protocol: TCP
      port: 5000
`

**Comment by grzesuav** [comment]
hi @wrkode , in case you want to add a label, it should be in a different way - just add a label/annotation to `parent` - as attachments are additional resources created. So in your case you do not need them

**Comment by grzesuav** [comment]
hmm wait, actually you are doing that, when you enable logging on `v7`, what do you get ?

**Comment by wrkode** [comment]
@grzesuav ,
thanks for chiming in.
I've raised logging to v7 and created `namespacefoo`
here is the result:
<script src="https://gist.github.com/wrkode/b96c858532e1b78e23b1c3e67c5fc9a2.js"></script>

**Comment by grzesuav** [comment]
@wrkode looking at https://metacontroller.github.io/metacontroller/api/decoratorcontroller.html#sync-hook-response

and  your snippet 
```python
namespace_labels = parent['metadata'].get('labels', {})
namespace_labels['testns'] = 'verified'
children['Namespace.v1'] = [{
    'apiVersion': 'v1',
    'kind': 'Namespace',
    'metadata': {
        'name': parent['metadata']['name'],
        'labels': namespace_labels
    }
}]

response = {
    "status": {},
    "attachments": children['Namespace.v1']
}

return flask.jsonify(response)
```
you are not setting `labels` in response,

there should be sth like 
```python
response = {
    "status": {},
    "labels": <set them here>
    "attachments": children['Namespace.v1']
}
```

**Comment by grzesuav** [comment]
@wrkode does it solved your issue ?

**Comment by wrkode** [comment]
@grzesuav tomorrow I'll be trying again and I'll report back.

**Comment by grzesuav** [comment]
@wrkode how it went ?

**Comment by grzesuav** [comment]
@wrkode please re-open in case it still does not work for you

**Comment by wrkode** [comment]
@grzesuav , sorry for not coming back to this. The issue was indeed solved. thank you
