### ISSUE TITLE
Initial setup of semantic release procedure

### ISSUE THREAD

**Issue by grzesuav** [metacontroller/metacontroller#8]
To make sure that all further commits match the conventions and are eligible to work with semantic release. 

In first order - install semantic pull request & commit watcher - https://github.com/apps/semantic-pull-requests - to watch for commits naming convention (https://github.com/AmitKumarDas/metac/pull/133)

and later on - setup semantic release - all work done in https://github.com/AmitKumarDas/metac/issues/64

**Comment by AmitKumarDas** [comment]
@grzesuav here are my thoughts to verify if current migrated code is same as master of gcp/metacontroller :

- we need to see if we can make use of multi stage Dockerfile (similar to metac) that runs UT as well as IT.
- Build local images & test against all the examples
- We can add more examples to verify further if needed. These examples can mirror our prod usage.

**Comment by grzesuav** [comment]
* I agree that we can run tests in docker (as it simplifies setup), but not sure why to bind it (as multistage build) to production image ? I do not see any advantage of this approach, it rather makes official Dockerfile "tidy" 
* it would be good to have separate tasks for that (it might be easier to create some tests on per-example basis) and maybe hook up as additional testing layer ?

**Comment by AmitKumarDas** [comment]
Having the test run within the dockerfile let's any contributor to test changes with docker as the only dependency on their workstation.

I am also proposing to move examples to a separate repository and have different test strategy once that's done.

**Comment by AmitKumarDas** [comment]
Having said so whatever is simple to begin with and verified the migration code can be tried out.

**Comment by grzesuav** [comment]
@AmitKumarDas I agree with having tests in docker make it easier to run, just wouldn't mix production image build with test run. I would keep them in two separate Dockerfiles - one for running test, other one - for building the production docker image.

**Comment by grzesuav** [comment]
Created another issue for that - https://github.com/metacontroller/metacontroller/issues/19

**Comment by grzesuav** [comment]
@AmitKumarDas I believe that basic procedure is done, if we need additional features we can create other issues and close this one.
