### ISSUE TITLE
metacontroller.app points to old repo

### ISSUE THREAD

**Issue by Kyrremann** [metacontroller/metacontroller#80]
I'm working on upgrading our metacontroller, and saw that http://metacontroller.app/ points to the old repo, and is still using old dependencies. 

Should maybe turn it into an placeholder page or point it to https://metacontroller.github.io/metacontroller/?

**Comment by grzesuav** [comment]
hi @Kyrremann , we are not in possession of that domain. cc: @AmitKumarDas 

Maybe @enisoc can help here ?

**Comment by Kyrremann** [comment]
Ah, that explains it! Hopefully that can be fixed :)

**Comment by enisoc** [comment]
I previously gave @AmitKumarDas the domain transfer auth code for metacontroller.app, but it looks like he either decided not to take it or just hasn't gotten around to it.

**Comment by AmitKumarDas** [comment]
I just could not get around it. I had even got the metacontroller.io domain (very costly).
Finally thought to use github pages and avoid renewing the domain every year.

**Comment by grzesuav** [comment]
can we just shutdown `metacontroller.app` ? To just not mislead other people ?

**Comment by grzesuav** [comment]
or it will expire soon ?

**Comment by enisoc** [comment]
@AmitKumarDas If you still want metacontroller.app, I think the transfer code I gave you in a DM on k8s slack should still work. If you don't want it anymore, I can shut it down as @grzesuav suggested. Otherwise it wouldn't expire until May.

**Comment by AmitKumarDas** [comment]
@enisoc I feel metacontroller.app is good to shutdown. 
In addition, do you both agree that current github pages model _i.e. https://metacontroller.github.io/metacontroller/_ is good thing to do. I really do not have much expertise here.

**Comment by Kyrremann** [comment]
I also think we should shut down metacontroller.app, as that is mainly the reason why I made this issue. I hadn't noticed that the app-site was the old project, while github pages was the new one.

Personally I like the github pages model, but maybe move the documention to the metacontroller.github.io-repo, so the address be a bit shorter and prettier?

**Comment by enisoc** [comment]
OK I have shut down the metacontroller.app Netlify site. If you want, I can set metacontroller.app to forward to https://metacontroller.github.io/metacontroller/ until it expires in May since I already paid through then. I can also go ahead and delete the domain entirely if you prefer.

**Comment by AmitKumarDas** [comment]
Thanks @enisoc . Forwarding metacontroller.app to GitHub pages site will be the best IMO.

**Comment by grzesuav** [comment]
thanks :) closing the issue
