### ISSUE TITLE
Metacontroller POD logs being flooded with 'unknown field "status"'

### ISSUE THREAD

**Issue by Arun-Trichy** [metacontroller/metacontroller#805]
After upgrading to Metacontroller version v4.10.3 and Kubernetes version 1.26
We are seeing these log lines keep coming very frequently

> {"level":"info","ts":1687327007.3534348,"msg":"unknown field \"status\"\n"}
{"level":"info","ts":1687327007.754479,"msg":"unknown field \"status\"\n"}
{"level":"info","ts":1687327007.958073,"msg":"unknown field \"status\"\n"}
{"level":"info","ts":1687327011.4584715,"msg":"unknown field \"status.observedGeneration\"\n"}
{"level":"info","ts":1687327011.4664521,"msg":"unknown field \"status.observedGeneration\"\n"}

It was not coming when we used kubernetes version 1.24
Are there any issues with using Metacontroller v4.10.3 and Kubernetes version 1.26 ?

**Comment by grzesuav** [comment]
hi, in future ping me on slack.

No idea about the issue, are those metacontroller logs ? It should definitely log more information. How looks like your Decorator/Composite controller definition and rest of the CRD's ?

**Comment by Arun-Trichy** [comment]
Hi @grzesuav ,

Thanks for responding, but got the issue sorted. It was to do with the status field missing in the CRD defenition

```yaml
status:
 type: object
``` 
After adding this field in the CRD the issue stopped.
