### ISSUE TITLE
Unable to set multiple ports in service-per-pod

### ISSUE THREAD

**Issue by tobias-zeptio** [metacontroller/metacontroller#83]
When i set multiple ports in the `service-per-pod-ports` annotations, the service creation fails because of missing port names. Are multiple ports supported, and is there a way to add the port names to the annotation? The hook only adds port and targetPort.

**Comment by fpetkovski** [comment]
This is fixed in https://github.com/metacontroller/metacontroller/pull/84

**Comment by tobias-zeptio** [comment]
Great @fpetkovski ! I see it's not being released now, do you know when it will be?

**Comment by grzesuav** [comment]
@tobias-zeptio this is `example` , not production code, nothing to release here

**Comment by tobias-zeptio** [comment]
Ah, of course. My bad!
